config/routes.rb
  Rails.application.routes.draw do

  get 'colleges/index/:stateid' => 'colleges#index', :as => 'college_index'
  get 'colleges/searchusers/:username' => 'colleges#searchusers', :as => 'colleges_search'

  get 'mailboxes/mailbox'
  get 'mailboxes/show/:id' => "mailboxes#show", :as => 'mailboxes_show'
  post 'mailboxes/compose'
  get 'mailboxes/destroy/:id' => 'mailboxes#destroy', :as => 'mailboxes_destroy'
  get 'mailboxes/new'
  post 'mailboxes/save'
  get 'mailboxes/outbox'
  get 'mailboxes/newest'
  get 'mailboxes/outboxdel/:id' => 'mailboxes#outboxdel', :as => 'mailboxes_outboxdel'

  get 'schools/index', :as => 'schools'
  get 'schools/profile'
  get 'schools/name'
  get 'schools/search'
  post 'schools/create'
  post 'profile/stuff' => 'profile#stuffupdate', :as => 'stuffs'
  patch 'profile/stuff' => 'profile#stuffupdate', :as => 'stuff'
  get 'profile/viewusers' => 'profile#viewUsers', :as => 'profile_viewusers'
  get 'profile/searchuser'
  get 'schools/edit/:id' => 'schools#edit',  as: 'schools_edit'
  patch 'schools/update/:id' => 'schools#update', as: 'schools_update'
  get 'schools/destroy/:id' => 'schools#destroy', :as => 'schools_destroy'
  get 'schools/ranking'
  get 'schools/state'
  get 'schools/statelist'
  get 'forums/index'
  get 'forums/:id/topics' => 'forums#topics', :as => 'forum_topic'
  post 'forums/topics/new' => 'forums#topic_new', :as => 'topic_new'
  get 'forums/topics/:topic/posts' => 'forums#posts', :as => 'forum_posts'
  post 'forums/posts/new' => 'forums#post_new', :as => 'post_new'
  get 'forums/new'
  # get 'forums/:id' => 'forums#show'
  get 'forums/post/:id' => 'forums#post', as: 'forum_post'
  post 'forums/create'
  post 'forums/postcreate'
  get 'forums/forumsearch'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
   

  get 'authentications/index'

  get 'members/index' #(signuup)
  get 'members/signup'
  post 'members/create'
  #get 'members/login'
  get 'members/verifieamil/:token' => 'members#verifiemail', as: 'member_verify'
  get 'members/collage/:stateid' => 'members#collage', as: 'member_collage'
  
  root 'homepage#index'

  get 'homepage/create'
  
  get 'myadvices/myadvice'
  get 'myadvice/blog/:id' => 'myadvices#blogdata', as: 'myadvices_blog' 
  get 'myadvices/new'
  post 'myadvices/create'
   # get 'admin/show/:id' => 'admins#show', as: 'show_admin'
  get 'announces/index'
  get 'announces/single/:id' => 'announces#single', as: 'announces_announce'
  get 'auth/:provider/callback' => 'authentications#create' 
  get 'logout' => 'authentications#destroy'

  get 'members/index'
  
  post 'subscribes/subscribe' 
  get 'subscribes/confirm/:token' => 'subscribes#confirm', as: 'subscribes_confirm'

  post 'subscribes/submitcontact'
  get 'subscribes/contactus'

  #--------profile routes-------------#
  get 'profile/index' => 'profile#index', :as => 'profile_index'
  get 'profile/login'
  post 'profile/create'
  get 'profile/mailbox'
  get 'profile/show/:id' => "profile#show", :as => 'profile_show'
  post 'profile/compose'
  get 'profile/destroy/:id' => 'profile#destroy', :as => 'profile_destroy'
  get 'profile/new'
  post 'profile/save'
  get 'profile/edit'
  post 'profile/update'
  get 'profile/settings'
  post 'profile/profilecreate'
  get 'profile/chnagepwd'
  post 'profile/changepwdcreate'
  get 'profile/forgotpassword'
  post 'profile/createforgotpassword'
  get 'profile/updatepassword/:token' => 'profile#updatepassword', :as => 'profile_updatepwd'
  post 'profile/createupdatepwd'
  get 'profile/profileupdates'
  get 'profile/schoolapplied'
  get 'profile/searchschool'
  get 'profile/like/:cuserid/:buserid' => 'profile#like', :as => 'profile_like'
  get 'profile/dislike/:cuserid/:buserid' => 'profile#dislike', :as => 'profile_dislike'
  get  'profile/commitschool/:cuurentuserid/:schoolname' => 'profile#commitschool', :as => 'profile_commitschool'
  get 'profile/comndestroy/:id' => 'profile#comndestroy', :as => 'profile_comndestroy'
  # resources :schools

  get 'member/:username' => 'profile#staticprofile', :as => 'static_profile'
  get 'profile/staticprofile'
  get 'profiles/all' => 'profile#staticbulk'
  get 'user/bookmark/:currentuserid/:bookmarkuserid' => 'profile#bookmark', :as => 'member_bookmark'
  get 'user/remove/:id' => 'profile#remove', :as => 'user_remove'
  
  post 'comments/create' => 'profile#commentcreate', :as => 'comment_new'
  post 'prof_cmn/create' => 'profile#prof_cmn_create', :as => 'prof_cmn_new'
  get 'profile/topusers' => 'profile#topusers', :as => 'topusers'
  
  get 'profile/bookmarklist'
  get 'bookmark/remove/:id' => 'profile#removebookmarklist', :as => 'booklist_remove'

  get 'schools/schoolappinfo/:schoolname' => 'schools#schoolappinfo', :as => 'school_appinfo'
  get 'profile/name' => 'profile#name', :as => 'profile_name'
  



end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  layout 'homepage'

  
  def index
  	@anouncements = Refineryannounce.last(2)
    @blogpost =  Refblog.last(2)
    @testimonials = Reftestimonial.all
    @posts = Refforum.last(7)
    @social = Refinery::Page.where(:slug => 'home_social_groups').first
    @users = Member.all
    @schools = Application.all
    @newcast = Refnewcast.all
    @allstates = State.all
     

    
    
    # @breakings = RefineryBreaking.all
  end
  def create
  
  end
  def blog
      
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
	def getpath id
		@dynamic = Refphoto.find(id).image_uid unless id.nil?
		@val = "/system/refinery/images/#{@dynamic}"
	end
end

app/views/homepage/_announcements.html.erb
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<div class="gdlr-item gdlr-blog-grid" >
<%unless @anouncements.empty? %>
<% @anouncements.each do |f| %>
	<div class="gdlr-ux gdlr-blog-grid-ux" style="opacity: 1; padding-top: 0px; margin-bottom: 0px;     margin-bottom: 2px;">
	<article id="post-870" class="post-870 post type-post status-publish format-standard has-post-thumbnail hentry category-blog category-fit-row tag-business tag-life-style tag-travel">
		<div class="gdlr-standard-style">
			<header class="post-header">
				<h3 class="gdlr-blog-title">
					<a href="<%= myadvices_blog_path(f.id) %>"><p style="font-size:13px;text-align:left;"><%= f.title %></p> </a>
				</h3>
			</header><!-- entry-header -->
		</div>
	</article>
	<lable style="text-align:justify;"><%=raw f.description.truncate(150) %></lable><!--  <div class="clear"></div> -->
	<a href="<%=announces_announce_path(f.id) %>">Read More</a>
	</div>

<% end %>
<a href="<%= announces_index_path %>" class="gdlr-button with-border excerpt-read-more" style="background-color: #72d5cd;border-color: #72d5cd;padding: 4px 23px;margin-left:26%;margin-top: 2px;">View More</a>
<% else %>
	<p style="text-align:center">No RECENT ANNONCEMENTS</p>
<%end%>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
</div>

app/views/homepage/_blog_single.html.erb
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<div class="gdlr-item gdlr-blog-grid" >
<%unless @blogpost.empty? %>
<% @blogpost.each do |f| %>
	<div class="gdlr-ux gdlr-blog-grid-ux" style="opacity: 1; padding-top: 0px; margin-bottom: 0px;     margin-bottom: 2px;">
	<article id="post-870" class="post-870 post type-post status-publish format-standard has-post-thumbnail hentry category-blog category-fit-row tag-business tag-life-style tag-travel">
		<div class="gdlr-standard-style">
			<header class="post-header">
				<h3 class="gdlr-blog-title" style="text-align: left;">
					<a href="<%= myadvices_blog_path(f.id) %>"><p style="font-size:13px;"><%= f.title %></p> </a>
				</h3>
			</header><!-- entry-header -->
		</div>
	</article>
	<lable style="text-align:justify;"><%=raw f.description.truncate(150) %>
	</lable><!--  <div class="clear"></div> -->
	<a href="<%= myadvices_blog_path(f.id) %>">Read More</a>
	</div>

<% end %>
<a href="<%= myadvices_myadvice_path %>" class="gdlr-button with-border excerpt-read-more" style="background-color: #72d5cd;border-color: #72d5cd;padding: 4px 23px;margin-left: 0px;margin-top: 2px;">View More</a>
<% else %>
	<P>No RECENT BLOG POST</P>
<%end%>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
</div>

app/views/homepage/_groupnews.html.erb
<section>
	<div class="gdlr-color-wrapper gdlr-show-all no-skin" style="padding:40px">
		<div class="container">
			<div class="four columns" >
				<div class="gdlr-shortcode-wrapper ">
					<h3 class="gdlr-divider thick" style="font-family:arial;font-size: 16px;text-align: center;  max-width: 93%;">Site Announcements</h3>

				</div>
				<div class="gdlr-item gdlr-divider-item"></div>
				<%=render :partial => 'homepage/announcements' %>
			</div>
			<div class="four columns" style="text-align: center;">
				<div class="gdlr-shortcode-wrapper ">
					<h3 class="gdlr-divider thick" style="font-family:arial;font-size: 16px;text-align: center;  max-width: 93%;">Recent Blog Post</h3>	
				</div>	
				<div class="gdlr-item gdlr-divider-item"></div>
				<%= render :partial => 'homepage/blog_single' %>
			</div>
			<div class="four columns" style="text-align: center;">
				<div class="gdlr-shortcode-wrapper">
					<h3 class="gdlr-divider thick" style="font-family:arial;font-size: 16px;text-align: center;  max-width: 93%;">Forum Threads</h3>	
				</div>	
				<div class="gdlr-item gdlr-divider-item"></div>
				<%= render :partial => 'homepage/posts' %>
			</div>
		</div>
	</div>
	<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
</section>

app/views/homepage/_posts.html.erb
<div class="blog-item-wrapper">
	<div class="blog-item-holder">
 <% unless @posts.empty? %>
 	
 
	
		<div class="clear"></div>
		<div class="twelve columns">
			<div class="gdlr-item gdlr-blog-widget">
				<div class="gdlr-ux gdlr-blog-widget-ux" style="opacity: 1; padding-top: 0px; margin-bottom: 0px;">
					<article id="post-2255" class="post-2255 post type-post status-publish format-standard has-post-thumbnail hentry category-post-slider tag-blog tag-life-style">
						<div class="gdlr-standard-style">
							
			<header class="post-header">
				
				
				<h2 class="gdlr-blog-title" style="text-align: left;">
				<% @posts.each do |a|%>
					<a href="<%= forum_topic_path(a.id) %>"><p style="font-size:13px;"><%= a.name %>.....</p> </a>
				<% end %>
				</h2>
				
				<a href="<%= forums_index_path %>" class="gdlr-button with-border excerpt-read-more" style="background-color: #72d5cd;border-color: #72d5cd;padding: 4px 23px;margin-left: 0px;margin-top: 2px;   font-family: arial;">View More</a>
			</header>	
							
							<div class="clear"></div>
						</div>
			</article><!-- #post -->
				</div>
			</div>
		</div>
		<div class="clear"></div>
		
		
		
	<% else %>
		<P>NO FORUM THREADS</P>
	<% end  %>
	<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
  </div>
</div>

app/views/homepage/_recentapp.html.erb
<section id="content-section-4">
<div class="gdlr-color-wrapper  gdlr-show-all no-skin" style="background-color: #ffffff;padding: 0;">
<div class="container">
<div class="gdlr-item-title-wrapper gdlr-item pos-center gdlr-nav-container "><div class="gdlr-item-title-head">
<i class="icon-angle-left gdlr-flex-prev"></i>
<h3 class="gdlr-item-title gdlr-skin-title gdlr-skin-border">RECENT APPLICATION UPDATES</h3>
<i class="icon-angle-right gdlr-flex-next"></i>
<div class="clear"></div></div>
<a class="gdlr-item-title-link" href="<%=profile_profileupdates_path%>">View All Updates</a></div>
<div class="course-item-wrapper">
<div class="gdlr-lms-course-grid2-wrapper gdlr-lms-carousel">
<div class="flexslider" data-type="carousel" data-nav-container="course-item-wrapper" data-columns="3">
<div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 1400%; margin-left: 0px;">
<li class="gdlr-lms-course-grid2 gdlr-lms-item " style="float: left; display: block; height: 375px; width: 350px;">
<%unless @schools.empty? %>
<% @schools.each do |user| %>
						<% @user=Member.find_by_id(user.user_id)

							
						%> 
<div class="gdlr-lms-course-content">
<h3 class="gdlr-lms-course-title">
<a href="#"><%=@user.username %><br>GPA: <%= number_with_precision(@user.gpa, precision: 2)  %><br>GMAT: <%=@user.gmat_score %></p> <%=user.status %>  at  <% sid =user.school.split('-') %> <% sname=user.school.split('-') %>
<%= sname[0] %> - <%= sname[1] %> </a>
</h3>
<div class="gdlr-lms-course-price">
<% if user.status == "Waitlisted" %>
	<i class="gdlr-icon icon-circle-blank" style="color: #91d549; font-size: 16px; "></i><%= user.status %>
														<% elsif user.status == "WL, Rejected" || user.status == "Rejected"%>
														<i class="gdlr-icon icon-remove" style="color: red; font-size: 16px; "></i><%= user.status %>
														<% elsif user.status == "WL, Accepted" %>
															<i class="gdlr-icon icon-ok" style="color: #91d549; font-size: 16px; "></i><%= user.status %>
															<% elsif user.status == "Accepted" %>
                                <%= user.status %>
                                  <i class="gdlr-icon icon-ok" style="color: #91d549; font-size: 16px;text-ailgn:center  "></i>
														<% else %>
															<i class="gdlr-icon icon-spinner" style="color: #91d549; font-size: 16px; "></i><%= user.status %>

														
													<% end %>

</div>
<div class="gdlr-lms-course-info">
<i class="icon-time">– Updated at <%= user.updated_at.strftime("%d-%m-%Y") %></i>
</div>
<div class="clear"></div></div></li>
<li class="gdlr-lms-course-grid2 gdlr-lms-item " style="float: left; display: block; height: 375px; width: 350px;">
<!-- <div class="gdlr-lms-course-thumbnail">
<a href="http://themes.goodlayers.com/clevercourse/course/starting-company-all-you-need-to-know-to-start-company/">

</div> -->
<div class="gdlr-lms-course-content">
<div class="clear"></div>
<%end %>
<% else %>
	<p style="color:black; font-size:16px">No Recent Application Updates</p>
<%end%>
</li>

</ul></div></div></div></div><div class="clear"></div></div></div><div class="clear"></div></section>
<div class="gdlr-item gdlr-divider-item"></div>

app/views/homepage/_searchschool.html.erb
<section id="content-section-5"><div class="gdlr-parallax-wrapper gdlr-background-image gdlr-show-all gdlr-skin-dark-skin" id="gdlr-parallax-wrapper-1" data-bgspeed="0.2" style="padding-top: 130px; padding-bottom: 90px; background-image: url(http://themes.goodlayers.com/clevercourse/wp-content/uploads/2014/08/search-bg1.jpg); background-position: 50% -86.4px;"><div class="container"><div class="gdlr-item-title-wrapper gdlr-item pos-center "><div class="gdlr-item-title-head"><h3 class="gdlr-item-title gdlr-skin-title gdlr-skin-border">Search For MBA Schools</h3><div class="clear"></div></div><div class="gdlr-item-title-divider"></div><div class="gdlr-item-title-caption gdlr-skin-info">Fill keywords to seek for MBA Schools</div></div><div class="course-search-wrapper"><form class="gdlr-lms-form" action="http://themes.goodlayers.com/clevercourse/">
	<div class="course-search-column gdlr-lms-1">
		<span class="gdlr-lms-combobox">
			<select name="state" id="state" style="width: 287px;
">
				<option value="">State</option>
				<% @allstates.each do |all_states| %>
				   <option value="<%= all_states.id %>"><%= all_states.name %></option>
				<% end %>

			</select>
		</span>
	</div>
	<div class="course-search-column gdlr-lms-3">
		<span class="gdlr-lms-combobox">
			<select name="course_type" id="gender" style="width: 431px;">
				<option value="">Type</option>
				<option value="online">Online Course</option>
				<option value="onsite">Onsite Course</option>
			</select>
		</span>	
	</div>
	<div class="course-search-column gdlr-lms-4">
		<input type="hidden" name="post_type" value="course">
		<input class="gdlr-lms-button" type="submit" value="Search!">
	</div>
	<div class="clear"></div>
</form>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
</div><div class="clear"></div></div></div><div class="clear"></div>
<div class="gdlr-lms-course-content"></div>
</section>
<div class="gdlr-item gdlr-divider-item"></div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript">
$("#state").change(function(){
   // alert("check");
   var stateid=$("#state").val();
   
    $.ajax({
              url: "<%=root_url %>colleges/index/"+stateid,
              context: document.body
            }).done(function(r) {

                   // alert(r);
                document.getElementById('undergraduate_school').innerHTML=r;
                
        });
    
});
</script>

app/views/homepage/_social.html.erb
<style type="text/css">
    .hover {
    position:relative;
    float:left;
    
}

.tooltip {
  top: -40px;
  background-color:black;
  color:white;
  border-radius:5px;
  opacity:0;
  position:absolute;
  padding: 3px;
  -webkit-transition: opacity 0.5s;
  -moz-transition:  opacity 0.5s;
  -ms-transition: opacity 0.5s;
  -o-transition:  opacity 0.5s;
  transition:  opacity 0.5s;
  width: 100px;
}

.hover:hover .tooltip {
    opacity:1;
}
header
{
  font-family: 'Lobster', cursive;
  text-align: center;
  font-size: 25px;  
}

#info
{
  font-size: 18px;
  color: #555;
  text-align: center;
  margin-bottom: 25px;
}

a{
  color: #074E8C;
}

.scrollbar
{
  margin-left: 0px;
  float: left;
  
  
  background: #F5F5F5;
  overflow-y: scroll;
  margin-bottom: 0px;
    width: 100%;
}

.force-overflow
{
  min-height: auto;
}

#wrapper
{
  text-align: center;
  width: auto;
  margin: auto;
}

/*
 *  STYLE 4
 */

#style-4::-webkit-scrollbar-track
{
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  background-color: #F5F5F5;
}

#style-4::-webkit-scrollbar
{
  width: 10px;
  background-color: #F5F5F5;
}

#style-4::-webkit-scrollbar-thumb
{
  background-color: #7E7ECD;
  border: 2px solid #7E7ECD;
}



</style>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<section id="content-section-8">
<div class="gdlr-color-wrapper  gdlr-show-all no-skin" style="background-color: #ffffff;  padding-bottom: 60px; ">
<div class="container">
<div class="gdlr-title-item" style="margin-bottom: 50px;">
<div class="gdlr-item-title-wrapper gdlr-item pos-center "><div class="gdlr-item-title-head">
<h3 class="gdlr-item-title gdlr-skin-title gdlr-skin-border">Social Media</h3>
<div class="clear"></div></div>
<div class="gdlr-item-title-divider"></div>

</div></div>
<div class="gdlr-banner-item-wrapper">
<div class="gdlr-banner-images gdlr-item" style="margin-bottom: 0px;">
<div class="flexslider" data-pausetime="7000" data-slidespeed="600" data-effect="fade" data-columns="3" data-type="carousel" data-nav-container="gdlr-banner-images"><div class="flex-viewport" style="overflow: hidden; position: relative;">
<ul class="slides" style="width: 600%; margin-left: 0px;">
<li style="float: left; display: block; width: 350px;"><a class="twitter-timeline" href="https://twitter.com/infombanumbers" data-widget-id="573467130869342208">Tweets by @infombanumbers</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			</li>
<li style="float: left; display: block; width: 350px;"><div class="" >
<div class="force-overflow"><div class="well" style="margin-bottom: 0px;">
<div class="fb-page" data-href="https://www.facebook.com/pages/MBA-Numbers/468649569971020?fref=ts" data-width="300" data-height="422" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pages/MBA-Numbers/468649569971020?fref=ts"><a href="https://www.facebook.com/pages/MBA-Numbers/468649569971020?fref=ts">MBA Numbers</a></blockquote></div></div></div></div></div></li>

<li style="float: left; display: block; width: 350px;">

<div class="scrollbar" id="style-4">
<div class="force-overflow">
<div class="" style="height: 470px; margin-bottom: 0px;  text-align: left;  padding-left: 10px;">
	<h6 style="color:rgb(132, 176, 226)">Breaking News</h6><hr>
	
	<% @newcast.each do |a|%>

	<p style="font-size:16px; color:black"><%= a.title  %></p>
	<p style="font-size:13px;text-align:justify"> 
			
			<%= raw a.description %>

	</p> 
	
	<% end %>
	</div>
	</div>
</div></li></ul></div><ul class="flex-direction-nav"><li><a class="flex-prev flex-disabled" href="#" tabindex="-1"><i class="icon-angle-left"></i></a></li><li><a class="flex-next flex-disabled" href="#" tabindex="-1"><i class="icon-angle-right"></i></a></li></ul></div></div></div><div class="clear"></div></div></div><div class="clear"></div></section>

app/views/homepage/_testimonials.html.erb
<section id="content-section-7">
<div class="gdlr-color-wrapper  gdlr-show-all no-skin" style="background-color: #f5f5f5; padding-top: 85px; padding-bottom: 45px; ">
<div class="container">
<div class="gdlr-testimonial-item-wrapper">
<div class="gdlr-item-title-wrapper gdlr-item pos-center gdlr-nav-container ">
<div class="gdlr-item-title-head">
<i class="icon-angle-left gdlr-flex-prev"></i>
<h3 class="gdlr-item-title gdlr-skin-title gdlr-skin-border" style="font-family:arial">What Student Say?</h3>
<i class="icon-angle-right gdlr-flex-next"></i>
<div class="clear"></div></div><div class="gdlr-item-title-divider"></div></div><div class="gdlr-item gdlr-testimonial-item carousel plain-style">
<div class="gdlr-ux gdlr-testimonial-ux" style="opacity: 1; padding-top: 0px; margin-bottom: 0px;"><div class="flexslider" data-type="carousel" data-nav-container="gdlr-testimonial-item" data-columns="1">
<div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 600%; margin-left: -1140px;">
<%@testimonials.each do |t| %><li class="testimonial-item" style="float: left; display: block; width: 1110px;"><div class="testimonial-content-wrapper"><div class="testimonial-content gdlr-skin-content"><%=raw t.content %></div><div class="testimonial-info"><span class="testimonial-author gdlr-skin-link-color"><%= t.name %></span><span class="testimonial-position gdlr-skin-info"><span>, </span><%= t.role %></span></div></div></li>
<%end %>
					</ul></div></div>
				</div></div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
	
</section>

app/views/homepage/new.html.erb
<div class="content-wrapper"><div id="primary" class="content-area">
<div id="content" class="site-content" role="main">
	<div class="gdlr-lms-content">
		<div class="gdlr-lms-container gdlr-lms-container">
			<div class="gdlr-lms-item">
								<%=form_tag homepage_create_path :class =>'gdlr-item gdlr-content-item' do |f| %>
					<p class="gdlr-lms-half-left">
						<label>Username *</label>
						
						<%= text_field_tag 'name' ,"",class: 'form-control' ,placeholder: 'Name' %>
					</p>
					<div class="clear"></div>
					<p class="gdlr-lms-half-left">
						<label>Password *</label>
						<%= password_field_tag 'name' , "",class: 'form-control' ,placeholder: 'Password' %>
					</p>
					<p class="gdlr-lms-half-right">
						 <label>Re Password *</label>
						 <%= text_field_tag 'name' , "",class: 'form-control' ,placeholder: 'Password' %>
					</p>
					<div class="clear"></div>
					<p class="gdlr-lms-half-left">
						<label>Zipcode *</label>
						<%= text_field_tag 'name' , "",class: 'form-control' ,placeholder: 'Zipcode' %>
					</p>
					<p class="gdlr-lms-half-right">
						 <label>Email id *</label>
						 <%= text_field_tag 'name' , "",class: 'form-control' ,placeholder: 'Email' %>
					</p>
					<div class="clear"></div>		
					<p class="gdlr-lms-half-left">
						<label>Gender *</label>
						<span class="gdlr-lms-combobox">
							<select name="gender" id="gender">
								<option value="m">Male</option>
								<option value="f">Female</option>
							</select>
						</span>					
					</p>
					<p class="gdlr-lms-half-right">
						 <label>Birth Date *</label>
						 <input type="text" name="birth_date" value="">
					</p>
					<div class="clear"></div>		
					<p class="gdlr-lms-half-left">
						<label>Email *</label>
						<input type="text" name="email" id="email" value="">
					</p>	
					<p class="gdlr-lms-half-right">
						<label>Phone</label>
						<input type="text" name="phone" id="phone" value="">
					</p>
					<div class="clear"></div>
					<p class="gdlr-lms-half-left">
						<label>Address *</label>
						<textarea name="address" id="address"></textarea>
					</p>
					<div class="clear"></div>				
					<p>
						<input type="hidden" name="action" value="create-new-user">
						<input type="submit" class="gdlr-lms-button" value="Create an account">
					</p>
				<%end %>
			</div>
		</div>
	</div>
</div>
</div>
		<div class="clear"></div>
	<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
		
	</div>