config/routes.rb
  Rails.application.routes.draw do

  get 'colleges/index/:stateid' => 'colleges#index', :as => 'college_index'
  get 'colleges/searchusers/:username' => 'colleges#searchusers', :as => 'colleges_search'

  get 'mailboxes/mailbox'
  get 'mailboxes/show/:id' => "mailboxes#show", :as => 'mailboxes_show'
  post 'mailboxes/compose'
  get 'mailboxes/destroy/:id' => 'mailboxes#destroy', :as => 'mailboxes_destroy'
  get 'mailboxes/new'
  post 'mailboxes/save'
  get 'mailboxes/outbox'
  get 'mailboxes/newest'
  get 'mailboxes/outboxdel/:id' => 'mailboxes#outboxdel', :as => 'mailboxes_outboxdel'

  get 'schools/index', :as => 'schools'
  get 'schools/profile'
  get 'schools/name'
  get 'schools/search'
  post 'schools/create'
  post 'profile/stuff' => 'profile#stuffupdate', :as => 'stuffs'
  patch 'profile/stuff' => 'profile#stuffupdate', :as => 'stuff'
  get 'profile/viewusers' => 'profile#viewUsers', :as => 'profile_viewusers'
  get 'profile/searchuser'
  get 'schools/edit/:id' => 'schools#edit',  as: 'schools_edit'
  patch 'schools/update/:id' => 'schools#update', as: 'schools_update'
  get 'schools/destroy/:id' => 'schools#destroy', :as => 'schools_destroy'
  get 'schools/ranking'
  get 'schools/state'
  get 'schools/statelist'
  get 'forums/index'
  get 'forums/:id/topics' => 'forums#topics', :as => 'forum_topic'
  post 'forums/topics/new' => 'forums#topic_new', :as => 'topic_new'
  get 'forums/topics/:topic/posts' => 'forums#posts', :as => 'forum_posts'
  post 'forums/posts/new' => 'forums#post_new', :as => 'post_new'
  get 'forums/new'
  # get 'forums/:id' => 'forums#show'
  get 'forums/post/:id' => 'forums#post', as: 'forum_post'
  post 'forums/create'
  post 'forums/postcreate'
  get 'forums/forumsearch'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
   

  get 'authentications/index'

  get 'members/index' #(signuup)
  get 'members/signup'
  post 'members/create'
  #get 'members/login'
  get 'members/verifieamil/:token' => 'members#verifiemail', as: 'member_verify'
  get 'members/collage/:stateid' => 'members#collage', as: 'member_collage'
  
  root 'homepage#index'

  get 'homepage/create'
  
  get 'myadvices/myadvice'
  get 'myadvice/blog/:id' => 'myadvices#blogdata', as: 'myadvices_blog' 
  get 'myadvices/new'
  post 'myadvices/create'
   # get 'admin/show/:id' => 'admins#show', as: 'show_admin'
  get 'announces/index'
  get 'announces/single/:id' => 'announces#single', as: 'announces_announce'
  get 'auth/:provider/callback' => 'authentications#create' 
  get 'logout' => 'authentications#destroy'

  get 'members/index'
  
  post 'subscribes/subscribe' 
  get 'subscribes/confirm/:token' => 'subscribes#confirm', as: 'subscribes_confirm'

  post 'subscribes/submitcontact'
  get 'subscribes/contactus'

  #--------profile routes-------------#
  get 'profile/index' => 'profile#index', :as => 'profile_index'
  get 'profile/login'
  post 'profile/create'
  get 'profile/mailbox'
  get 'profile/show/:id' => "profile#show", :as => 'profile_show'
  post 'profile/compose'
  get 'profile/destroy/:id' => 'profile#destroy', :as => 'profile_destroy'
  get 'profile/new'
  post 'profile/save'
  get 'profile/edit'
  post 'profile/update'
  get 'profile/settings'
  post 'profile/profilecreate'
  get 'profile/chnagepwd'
  post 'profile/changepwdcreate'
  get 'profile/forgotpassword'
  post 'profile/createforgotpassword'
  get 'profile/updatepassword/:token' => 'profile#updatepassword', :as => 'profile_updatepwd'
  post 'profile/createupdatepwd'
  get 'profile/profileupdates'
  get 'profile/schoolapplied'
  get 'profile/searchschool'
  get 'profile/like/:cuserid/:buserid' => 'profile#like', :as => 'profile_like'
  get 'profile/dislike/:cuserid/:buserid' => 'profile#dislike', :as => 'profile_dislike'
  get  'profile/commitschool/:cuurentuserid/:schoolname' => 'profile#commitschool', :as => 'profile_commitschool'
  get 'profile/comndestroy/:id' => 'profile#comndestroy', :as => 'profile_comndestroy'
  # resources :schools

  get 'member/:username' => 'profile#staticprofile', :as => 'static_profile'
  get 'profile/staticprofile'
  get 'profiles/all' => 'profile#staticbulk'
  get 'user/bookmark/:currentuserid/:bookmarkuserid' => 'profile#bookmark', :as => 'member_bookmark'
  get 'user/remove/:id' => 'profile#remove', :as => 'user_remove'
  
  post 'comments/create' => 'profile#commentcreate', :as => 'comment_new'
  post 'prof_cmn/create' => 'profile#prof_cmn_create', :as => 'prof_cmn_new'
  get 'profile/topusers' => 'profile#topusers', :as => 'topusers'
  
  get 'profile/bookmarklist'
  get 'bookmark/remove/:id' => 'profile#removebookmarklist', :as => 'booklist_remove'

  get 'schools/schoolappinfo/:schoolname' => 'schools#schoolappinfo', :as => 'school_appinfo'
  get 'profile/name' => 'profile#name', :as => 'profile_name'
  



end

app/controllers/mailboxes_controller.rb
 class MailboxesController < ApplicationController
  layout 'homepage'
 before_action :authenticate_user
 
  def mailbox
    @title = 'Mailbox'
    @outbox = Outbox.where('member_id=?',session[:user_id])
    @inboxreciver = Outbox.where('name=? AND receiver_at=?',Member.find(session[:user_id]).email,TRUE).paginate(:page => params[:page], :per_page => 20)
  end

  def outbox
    @title = 'Mailbox'
    # Client.where("orders_count = ? AND locked = ?", params[:orders], false)
    @senderoutbox = Outbox.where('member_id=? AND sender_at=?',session[:user_id],TRUE).paginate(:page => params[:page], :per_page => 20)
    @senderinbox = Outbox.where('member_id=? AND sender_at=?',session[:user_id],FALSE).paginate(:page => params[:page], :per_page => 20)
    
    @inbox = Outbox.where('name=? AND sender_at=?',Member.find(session[:user_id]).email,TRUE)
  end

  def newest
    @title = 'Mailbox'
    @outbox = Outbox.where('member_id=?',session[:user_id])
    @inbox = Outbox.where('name=?',Member.find(session[:user_id]).email)
  end
  
  def show
   @reply = Reply.where('outbox_id=?', params[:id])
   @inbox = Outbox.find(params[:id])
  end

  def new
    @reply = Reply.new
  end

  def save
    @reply = Reply.new(reply_params)
    if @reply.save
      redirect_to(:action => 'mailbox')
    else
    render :action => 'show' 
    end

  end



  def compose
     UserMailer.sent(params).deliver!
     @outbox = Outbox.new(:name => params[:name], :subject => params[:subject], 
      :message => params[:message], :member_id => session[:user_id], :from => params[:from],:sender_at => params[:sender_at],:receiver_at => params[:receiver_at])
     @outbox.from = current_user.email
      if @outbox.save
        flash[:success] = 'Message send sucessfully'
        redirect_to  :action => 'mailbox' , :alert => "Message send sucessfully"
      end
  end
  def destroy
    @outbox = Outbox.find(params[:id]).update(:receiver_at => 'FALSE')

    if @outbox
      redirect_to :action => 'mailbox'
    end

  end
  def outboxdel
 
    @outboxdel= Outbox.find_by_id(params[:id]).update(:sender_at => 'FALSE')
    if @outboxdel
      redirect_to mailboxes_outbox_path
    end

  end



  def reply_params
      params.permit(:outbox_id, :message)
      
   end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/mailbox.html.erb
<style>
	
#th {
    background-color: #3E6AA7;
    color:white;
   font-family: Verdana,Arial,Helvetica,sans-serif;
   font-weight: normal;padding: 9px;text-transform: uppercase;
   font-size: 14px;

    
}
.style-1 tr td{

	font-family: arial;
	font-size: 50;
}
</style>





<div class="gdlr-lms-content">
	<div class="two columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="eight columns">
			<div class="gdlr-item gdlr-tab-item horizontal"><div class="tab-title-wrapper"><a href="<%=mailboxes_mailbox_path %>"><h4 class="tab-title active"><i class="icon-inbox"></i><span>Inbox</span></h4></a><a href="<%=mailboxes_outbox_path %>"><h4 class="tab-title"><i class="icon-share-alt"></i><span>Outbox</span></h4></a><a href="<%=mailboxes_newest_path %>"><h4 class="tab-title"><i class="icon-edit"></i><span>Compose</span></h4></a></div><div class="tab-content-wrapper">
			<i class="icon-chevron-left" ></i>
	<i class="icon-chevron-left" ></i><a href="<%=profile_index_path %>">Back to profile</a>
			<div class="tab-content active">
			<table class="style-1">
				<tbody>
				<tr>
				<th id="th" style="text-align:left;width: 25%;">From
				</th><th id="th" style="text-align:center width:50% ">Message</th>
				<th id ="th" style="width:25%">Newest</th>
				</tr>

				
				<% @inboxreciver.each do |f| %>
				<tr>
				<td style="width:25%">
				<!-- <input type="checkbox" id="msg_17231" name="msg_17231" style="padding:0; margin:left"> -->
				<b><%=f.from %></b><br>
				<a href="<%=mailboxes_show_path(f.id) %>" style="font-size:14px"><%=f.subject %></a><br>
				<a href="<%=mailboxes_destroy_path(f.id)%>" style="color:#d6724f"><i class="gdlr-icon icon-remove" ></i>Delete</a></td>
				<td style="width:50%"><a href="<%=mailboxes_show_path(f.id) %>" style="color:black"><b><%= f.message %></b></a></td>
				<td style="25%"><%= f.created_at.strftime("%B %d, %Y %H:%M") %></td>					
				</tr>
				<%end %>
		

				</tbody>
				</table>
					
					</div>


					

			</div></div><div class="clear"></div></div>
	</div>

	<div class="one columns"></div>

	<div class="one columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="clear"></div>
</div>

app/views/mailboxes/newest.html.erb
<style>
	
#th {
    background-color: #3E6AA7;
    color:white;
   font-family: Verdana,Arial,Helvetica,sans-serif;
   font-weight: normal;padding: 9px;text-transform: uppercase;
   font-size: 14px;

    
}
.style-1 tr td{

	font-family: arial;
	font-size: 50;
}
</style>





<div class="gdlr-lms-content">
	<div class="two columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="eight columns">
			<div class="gdlr-item gdlr-tab-item horizontal"><div class="tab-title-wrapper"><a href="<%=mailboxes_mailbox_path %>"><h4 class="tab-title" ><i class="icon-inbox"></i><span>Inbox</span></h4></a><a href="<%=mailboxes_outbox_path %>"><h4 class="tab-title"><i class="icon-share-alt"></i><span>Outbox</span></h4></a><a href="<%=mailboxes_newest_path %>"><h4 class="tab-title active"><i class="icon-edit"></i><span>Compose</span></h4></a></div><div class="tab-content-wrapper">

					<i class="icon-chevron-left" ></i>
	<i class="icon-chevron-left" ></i><a href="<%=profile_index_path %>">Back to profile</a>
					<div class="tab-content active">
					<%=form_tag mailboxes_compose_path, :class =>'gdlr-item gdlr-content-item gdlr-lms-form' do |f| %>
					<input type="hidden" name="from" value=<%= @usermail %>>
					<input type="hidden" name="sender_at" value="TRUE">
					<input type="hidden" name="receiver_at" value="TRUE">
		<p>Email id:*<br>
		<span id="error1" style="color:red"></span>
		<span class="wpcf7-form-control-wrap your-name">
		<%= text_field_tag 'name' , "",class: 'form-control' ,placeholder: 'Email' ,
		:id => "name"%>
		</span> </p>
		<p>Subject<br>
		<span class="wpcf7-form-control-wrap your-subject">
			<%= text_field_tag 'subject' , "",class: 'form-control' ,placeholder: 'Subject' %>
		</span> </p>
		<p>Your Message<br>
		<span class="wpcf7-form-control-wrap your-message">
		<%= text_area_tag 'message' , "",class: 'form-control' ,placeholder: 'Message' %></span> </p>
		<p></p>
		<div class="wpcf7-response-output wpcf7-display-none"></div>
		<%= submit_tag 'Send',class: 'wpcf7-form-control wpcf7-submit',name: 'send',:onclick => 'return validatesform();' %>
		
		</div>
	<%end%>

			</div></div><div class="clear"></div></div>
	</div>
	<div class="one columns"></div>
	<div class="one columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="clear"></div>
</div>

<script type="text/javascript">
	function validatesform()
	{
		var name=document.getElementById('name').value
		var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    
		if(name == "")
		{
			document.getElementById('error1').innerHTML ="Please Enter Email";
			return false;
		}
		else if(!re.test(name))
		{
			document.getElementById('error1').innerHTML ="Please Enter Valid Email";
			return false;
		}
		
	}
</script>

app/views/mailboxes/outbox.html.erb
<style>
	
#th {
    background-color: #3E6AA7;
    color:white;
   font-family: Verdana,Arial,Helvetica,sans-serif;
   font-weight: normal;padding: 9px;text-transform: uppercase;
   font-size: 14px;

    
}
.style-1 tr td{

	font-family: arial;
	font-size: 50;
}
</style>





<div class="gdlr-lms-content">
	<div class="two columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="eight columns">
			<div class="gdlr-item gdlr-tab-item horizontal"><div class="tab-title-wrapper"><a href="<%=mailboxes_mailbox_path %>"><h4 class="tab-title"><i class="icon-inbox"></i><span>Inbox</span></h4></a>
			<a href="<%=mailboxes_outbox_path %>"><h4 class="tab-title active"><i class="icon-share-alt"></i><span>Outbox</span></h4></a><a href="<%=mailboxes_newest_path %>"><h4 class="tab-title"><i class="icon-edit"></i><span>Compose</span></h4></a></div><div class="tab-content-wrapper">
				<i class="icon-chevron-left" ></i>
	<i class="icon-chevron-left" ></i><a href="<%=profile_index_path %>">Back to profile</a>

			<div class="tab-content ">
			<table class="style-1">
				<tbody>
				<tr>
				<th id="th" style="text-align:left;width: 25%;">To
				</th><th id="th" style="text-align:center width:50% ">Message</th>
				<th id ="th" style="width:25%">Newest</th>
				</tr>	
				</tbody>
				</table>
					
					</div>


					<div class="tab-content active">
					<table class="style-1">

				<tbody>

				<tr>
				<th id="th" style="text-align:left;width:25%;">To
				</th><th id="th" style="text-align:center; width:50% " >Message</th>
				<th id ="th" style="width:25%">Newest</th>
				</tr>
				<tr>
				<% @senderoutbox.each do |f| %>
				
				<td style="width:25%">
				<b><%=f.name %></b><br>
				<a href="#" style="font-size:14px"><%=f.subject %></a><br>
				<a href="<%= mailboxes_outboxdel_path(f.id) %>" style="color:#d6724f"><i class="gdlr-icon icon-remove" ></i>Delete</a></td>
				<td style="width:50%"><b><%= f.message %></b></td>
				<td style="25%"><%= f.created_at.strftime("%B %d, %Y %H:%M") %></td>	</tr>					
		
				<%end %>
				</tbody>
				</table>
					</div>
					<div class="tab-content">
					</div></div><div class="clear"></div></div>
	</div>
	<div class="one columns"></div>
	<div class="one columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="clear"></div>
</div>

app/views/mailboxes/show.html.erb
<div class="gdlr-lms-content">
	<div class="two columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>
	<div class="eight columns">
			<div class="gdlr-item gdlr-tab-item horizontal">
			<div class="tab-title-wrapper">
			<h4 class="tab-title active">
			<i class="icon-inbox"></i><span>Inbox</span></h4>
			<h4 class="tab-title ">
			<i class="icon-share-alt"></i><a href="<%=mailboxes_mailbox_path %>">Outbox</a></h4><a href="<%=mailboxes_mailbox_path %>"><h4 class="tab-title "><i class="icon-edit"></i>Compose</h4></a></div><div class="tab-content-wrapper"><div class="tab-content active">
			<div>
			 <p><a href="/mailboxes/mailbox" style="color:blue; font-family:arial">Back to inbox</a><br>
			 </p>
			 <p><a href="#">Mba Numbers</a><br></p>	
			 <div class="gdlr-divider thick"></div>
			 
            <p style="color:black"><%=@inbox.subject%></p>
       
						<%=@inbox.message %>
				<div class="gdlr-divider dotted"></div>
				<%# @reply.each do |f| %>
				<%#= f.message %>
				<!-- <div class="gdlr-divider dotted"></div> -->
				<%#end %>
						
			<!-- <div class="gdlr-divider dotted"></div> -->
						<!-- <p>Your Reply<br> -->
				<%#=form_tag mailboxes_save_path %>
				<!-- <input type="hidden" name="outbox_id" value='<%#= params[:id]%>'> -->			
				<!-- <span class="gdlr-item gdlr-content-item gdlr-lms-form">
		<%#= text_area_tag 'message' , "",class: 'form-control' ,placeholder: 'Message' %>
		</span> </p> -->
   				<%#= submit_tag 'Send',class: 'wpcf7-form-control wpcf7-submit',name: 'send' %>
			</div>
			</div>
			</div>
			</div>
			</div>
			<div class="clear"></div>
			</div>