config/routes.rb
  Rails.application.routes.draw do

  get 'colleges/index/:stateid' => 'colleges#index', :as => 'college_index'
  get 'colleges/searchusers/:username' => 'colleges#searchusers', :as => 'colleges_search'

  get 'mailboxes/mailbox'
  get 'mailboxes/show/:id' => "mailboxes#show", :as => 'mailboxes_show'
  post 'mailboxes/compose'
  get 'mailboxes/destroy/:id' => 'mailboxes#destroy', :as => 'mailboxes_destroy'
  get 'mailboxes/new'
  post 'mailboxes/save'
  get 'mailboxes/outbox'
  get 'mailboxes/newest'
  get 'mailboxes/outboxdel/:id' => 'mailboxes#outboxdel', :as => 'mailboxes_outboxdel'

  get 'schools/index', :as => 'schools'
  get 'schools/profile'
  get 'schools/name'
  get 'schools/search'
  post 'schools/create'
  post 'profile/stuff' => 'profile#stuffupdate', :as => 'stuffs'
  patch 'profile/stuff' => 'profile#stuffupdate', :as => 'stuff'
  get 'profile/viewusers' => 'profile#viewUsers', :as => 'profile_viewusers'
  get 'profile/searchuser'
  get 'schools/edit/:id' => 'schools#edit',  as: 'schools_edit'
  patch 'schools/update/:id' => 'schools#update', as: 'schools_update'
  get 'schools/destroy/:id' => 'schools#destroy', :as => 'schools_destroy'
  get 'schools/ranking'
  get 'schools/state'
  get 'schools/statelist'
  get 'forums/index'
  get 'forums/:id/topics' => 'forums#topics', :as => 'forum_topic'
  post 'forums/topics/new' => 'forums#topic_new', :as => 'topic_new'
  get 'forums/topics/:topic/posts' => 'forums#posts', :as => 'forum_posts'
  post 'forums/posts/new' => 'forums#post_new', :as => 'post_new'
  get 'forums/new'
  # get 'forums/:id' => 'forums#show'
  get 'forums/post/:id' => 'forums#post', as: 'forum_post'
  post 'forums/create'
  post 'forums/postcreate'
  get 'forums/forumsearch'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
   

  get 'authentications/index'

  get 'members/index' #(signuup)
  get 'members/signup'
  post 'members/create'
  #get 'members/login'
  get 'members/verifieamil/:token' => 'members#verifiemail', as: 'member_verify'
  get 'members/collage/:stateid' => 'members#collage', as: 'member_collage'
  
  root 'homepage#index'

  get 'homepage/create'
  
  get 'myadvices/myadvice'
  get 'myadvice/blog/:id' => 'myadvices#blogdata', as: 'myadvices_blog' 
  get 'myadvices/new'
  post 'myadvices/create'
   # get 'admin/show/:id' => 'admins#show', as: 'show_admin'
  get 'announces/index'
  get 'announces/single/:id' => 'announces#single', as: 'announces_announce'
  get 'auth/:provider/callback' => 'authentications#create' 
  get 'logout' => 'authentications#destroy'

  get 'members/index'
  
  post 'subscribes/subscribe' 
  get 'subscribes/confirm/:token' => 'subscribes#confirm', as: 'subscribes_confirm'

  post 'subscribes/submitcontact'
  get 'subscribes/contactus'

  #--------profile routes-------------#
  get 'profile/index' => 'profile#index', :as => 'profile_index'
  get 'profile/login'
  post 'profile/create'
  get 'profile/mailbox'
  get 'profile/show/:id' => "profile#show", :as => 'profile_show'
  post 'profile/compose'
  get 'profile/destroy/:id' => 'profile#destroy', :as => 'profile_destroy'
  get 'profile/new'
  post 'profile/save'
  get 'profile/edit'
  post 'profile/update'
  get 'profile/settings'
  post 'profile/profilecreate'
  get 'profile/chnagepwd'
  post 'profile/changepwdcreate'
  get 'profile/forgotpassword'
  post 'profile/createforgotpassword'
  get 'profile/updatepassword/:token' => 'profile#updatepassword', :as => 'profile_updatepwd'
  post 'profile/createupdatepwd'
  get 'profile/profileupdates'
  get 'profile/schoolapplied'
  get 'profile/searchschool'
  get 'profile/like/:cuserid/:buserid' => 'profile#like', :as => 'profile_like'
  get 'profile/dislike/:cuserid/:buserid' => 'profile#dislike', :as => 'profile_dislike'
  get  'profile/commitschool/:cuurentuserid/:schoolname' => 'profile#commitschool', :as => 'profile_commitschool'
  get 'profile/comndestroy/:id' => 'profile#comndestroy', :as => 'profile_comndestroy'
  # resources :schools

  get 'member/:username' => 'profile#staticprofile', :as => 'static_profile'
  get 'profile/staticprofile'
  get 'profiles/all' => 'profile#staticbulk'
  get 'user/bookmark/:currentuserid/:bookmarkuserid' => 'profile#bookmark', :as => 'member_bookmark'
  get 'user/remove/:id' => 'profile#remove', :as => 'user_remove'
  
  post 'comments/create' => 'profile#commentcreate', :as => 'comment_new'
  post 'prof_cmn/create' => 'profile#prof_cmn_create', :as => 'prof_cmn_new'
  get 'profile/topusers' => 'profile#topusers', :as => 'topusers'
  
  get 'profile/bookmarklist'
  get 'bookmark/remove/:id' => 'profile#removebookmarklist', :as => 'booklist_remove'

  get 'schools/schoolappinfo/:schoolname' => 'schools#schoolappinfo', :as => 'school_appinfo'
  get 'profile/name' => 'profile#name', :as => 'profile_name'
  



end

app/models/school.rb
class School < ActiveRecord::Base
	dragonfly_accessor :image
	validates :school, :presence => true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	layout 'schools'
  before_action :authenticate_user, :only => [:profile, :create, :destroy, :update, :edit]
  before_action :check_auth, :only => [:edit, :update, :destroy]
  def index
  	@title="MBA Schools"
  	# @schools= School.paginate(:page => params[:page], :per_page => 10)
    @q = School.ransack(params[:q]) 
    @schools = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 20).order('business_school ASC')
 
  end

  def profile
  	@title="Add Application"
    @school_name=School.order('university ASC')
    @app_data=Application.order('school DSC')
    
  	
  end
  def ranking
    @title="Browse MBA schools by Ranking"
    @schools = School.order('forbes').paginate(:page => params[:page], :per_page => 20)
    # binding.pry
  end
  def state
    @title = "Schools List By State"
    @states= State.order('name').paginate(:page => params[:page], :per_page => 20)
   end

    def statelist
    @title = "Schools State Wise List"
    end


  def edit
   @title="Edit Application"
    @app_data = Application.find(params[:id])
    @school_name = School.order('university ASC')
  end
  def schoolappinfo
    @school=Application.find_by_school(params[:schoolname])
    @title=params[:schoolname]
  end


  def update
      @schools = Application.find(params[:id])
    if @schools.update(req_params) 
      redirect_to profile_index_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @app_data = Application.find(params[:id])
    
    if @app_data.school==current_user.commitschool
      current_user
    end
    @app_data.destroy
    redirect_to profile_index_path
  end


  def name
  	@title="Schools List By Name"
    @schools= School.order('business_school').paginate(:page => params[:page], :per_page => 15)
  end

  def create
    
    if params[:school].empty?
        flash[:error]="School can't be blank"
       redirect_to schools_profile_path
      elsif params[:status].empty?
        flash[:error]="Status can't be blank"
        redirect_to schools_profile_path
      elsif params[:program].empty?
        flash[:error]="Program can't be blank"
        redirect_to schools_profile_path
      else
        school_app=Application.new(req_params)
       school_app.user_id = session[:user_id]
       if school_app.save
         flash[:success] = "Application added"
         redirect_to profile_index_path
        end  
    end
  end

  private
  def req_params
    params.permit(:school,:status,:program,:interviewdate,:choice,:received,:descion,:scholarship,:interview)
  end
  def check_auth
    if Application.find(params[:id]).user_id != session[:user_id]
      render :text => "You are not authorized"
    end
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/index.html.erb
 
<div class="gdlr-item gdlr-divider-item"></div>
<div class="gdlr-lms-container gdlr-lms-container">
        <div class="gdlr-lms-item">
 <div  class= "ten column" id='profind'>
<div style="margin-top:18px">
<div class="gdlr-item gdlr-tab-item horizontal" id="table">
<div class="tab-title-wrapper">
	<a href="<%=schools_path %>">
		<h4 class="tab-title active">
		<span>MBA Schools list</span></h4>
	</a>
	<a href="<%=schools_ranking_path %>"><h4 class="tab-title"><span>By Ranking</span></h4></a>
	<!-- <a href="<%=schools_name_path %>"><h4 class="tab-title"><span>By Name</span></h4></a> -->
	<a href="<%=schools_state_path %>"><h4 class="tab-title"><span>By State</span></h4></a>
	<div class="gdlr-lms-content">

		<div id="tribe-events-bar">

	<!-- <form id="tribe-bar-form" class="tribe-clearfix tribe-bar-full" name="tribe-bar-form" method="post" action="http://themes.goodlayers.com/clevercourse/events?post_type=tribe_events&amp;eventDisplay=default">
	 -->
		<!-- Mobile Filters Toggle -->
	<%=search_form_for @q, :html => { :class => 'tribe-clearfix tribe-bar-full', :id => 'tribe-bar-form'} do |f| %>

			<div class="tribe-bar-filters">
				<div class="tribe-bar-filters-inner tribe-clearfix">
					<div class="tribe-bar-date-filter">
							<div id="tribe-bar-dates">
							 <label class="label-tribe-bar-date" for="tribe-bar-date">Search</label>
							 <!-- <input type="text" name="tribe-bar-date" style="position: relative;" id="tribe-bar-date" value="" placeholder="Date"> -->
							 <%= f.search_field :university_cont, id:'tribe-bar-search', placeholder:'University Name', :style => 'outline:none' %>
							</div>
							<input type="hidden" name="tribe-bar-date-day" id="tribe-bar-date-day" class="tribe-no-param" value="">
					</div>
					<div class="tribe-bar-search-filter">
						<label class="label-tribe-bar-search" for="tribe-bar-search">Search</label>
						<%= f.search_field :business_school_cont, id:'tribe-bar-search', placeholder:'School Name', :style => 'outline:none' %> 
					</div>
					<div class="tribe-bar-submit">
						<%= f.submit%>
					</div>
					<!-- .tribe-bar-submit -->
				</div>
				<!-- .tribe-bar-filters-inner -->
			</div><!-- .tribe-bar-filters -->
	<% end %>
</div>
<div>
	<!-- #Temproray -->
	 
</div>
	<!-- <div class="well"  > -->
		<div>
		 
			<table width="100%" border="1" cellspacing="8" cellpadding="0" class="drawreq_table">
                       <tr><th id="th" style="border-right:none;border-bottom:none"></th>
                <th id ="th" style="border-left:none" rowspan="2"  width="38%">Business School</th>
                <th id ="th" rowspan="2" width="4%">University</th>
                <th id ="th" rowspan="2" width="4%">State</th>
                <th id ="th" rowspan="2" width="4%">City</th>
                <th id ="th" colspan="4" width="27%">Ranks</th>
                        </tr>
                        <tr>

                        <th  id ="th" width="12%" style="border:#3E6AA7;border-bottom:1px solid #000" ></th>
                        <th  id ="th" width="11%">Forbes</th>
                        <th id ="th">USN</th>
                    </tr>
                    <% @schools.each do |t| %>
                    <tr style="font-size:15px">
                            <td style="border-right:none"><img alt="Icon" src="<%= t.image.thumb('150x150').url %>" style="width: 60px; height: 41px;" />
                    </td>
                            <td style="border-left:none"> <a href="<%= school_appinfo_path(t.business_school) %>" style="color:#453232;">
                                    <%= t.business_school%>
                                    </a> </td>
                            <td style="color:#453232;"> <%=t.university %></td>
                            <td style="color:#453232;">
                    <%= State.find_by_id(t.state_id).name%></td>
                            
                            <td style="color:#453232;"><%=t.city %></td>
                            <td style="color:#453232;"><%=t.forbes %></td>
                    <td style="color:#453232;"><%=t.US_News_Ranking %></td>
                    
                    </tr>
                    <%end%>
                    
                    
               </table> 
		</div>
		<div class="gdlr-item gdlr-divider-item"></div>
		<%= will_paginate @schools, :class => 'gdlr-pagination'%>
	<!-- </div> -->
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</div>
</div>
</div>
<div class="profile_blog_rgt" style="border:none">
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                </div>
</div>
</div>

app/views/schools/name.html.erb
<div id="profind">
<div class="well">

<div class="gdlr-item gdlr-tab-item horizontal">
<div class="tab-title-wrapper">
<a href="<%=schools_path %>"><h4 class="tab-title">
<span>Schools List</span></h4></a>
<a href="<%=schools_ranking_path %>"><h4 class="tab-title"><span>By Ranking</span></h4></a>
<a href="<%=schools_state_path %>"><h4 class="tab-title"><span>By State</span></h4></a>

<div class="gdlr-lms-content">
	<div class="eight columns">
	
		<div style="margin-left:1px;margin-right:1px">
			<div class="eleven columns">
				<div class="gdlr-item-title-wrapper gdlr-item pos-left borderme" style="margin-left: 1px;">
						<div class="gdlr-space" style="margin-top: 40px;"></div>
						<table class="style-2">
						<thead>
							<tr>
								<th id="th">Icon</th>
								<th id="th">Business school name</th>

							</tr>
						</thead>
						<tbody style="text-align:left">
							<% @schools.each do |t| %>
							<tr>
								<td><img alt="Icon" src="<%= t.image.thumb('150x150').url %>" style="width: 100px; height: 41px;" /></td>
								<td style="padding:10px"><a href="<%= school_appinfo_path(t.business_school) %>" style='color:inherit'><%= t.business_school %> </a></td>
							</tr>
							<%end %>
						</tbody>
						</table>
				</div>
				<%= will_paginate @schools, :class => 'gdlr-pagination'%>
			</div>
			<div class="one columns"></div>
		</div>
	</div>

	
	<div class="clear"></div>
		
</div>

</div>
</div>
</div>

app/views/schools/profile.html.erb
<div class="gdlr-lms-container gdlr-lms-container">
                    <div class="gdlr-lms-item">
                     <div class="profile_blog_lft" style="border:none">
                <%#= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                <%=image_tag '3.jpg' %>
                </div>                     

                <div class="nine column" style="padding:10px">
                    <%= form_tag schools_create_path, :class => 'gdlr-lms-form' do |f| %>

                    <p class="gdlr-lms-half-left">
            <label >Choose a School*</label>
            <span class="gdlr-lms-combobox" >
           <select  name="school" id="school" style="width:100% ">
                            <option value="" >-----------Select School----------</option>
                            <% @school_name.each do |sn| %>
                                 <option value="<%= sn.university%>-<%= sn.business_school%>-<%= sn.id %>">
                                       <%= sn.university %>-<%= sn.business_school  %> 
                                 </option>
                            <% end %>
                                  
                            </select>
            
                        </span></p>
                        <p class="gdlr-lms-half-left">
            <label><span>Interview Date*</span></label>
             
            <input type="radio" name="interview" id="intqyes" value="yes" style=" ">&nbspYes
        <input type="radio" name="interview" id="intqno"  value="no" >&nbspNo
                        
        
                        
            </p>
                        
                        <p class="gdlr-lms-half-left" style="display:none;" id="intdate" style="  width: 100%;">
            
            <label >Interview Date</label>
            
            
            <span class="gdlr-lms-combobox" >
            
                        <input type="text" name="interviewdate" id="interviewdate" placeholder="DD/MM/YYYY" style="  background-color: white;" type="text" onfocus="(this.type='date')" >
                                  
    
                        </span></p>

                        

                        <p class="gdlr-lms-half-left">
            <label >Status*</label>
            <span class="gdlr-lms-combobox" >
                            <select  name="status" id="status" style="width: 100%;">
                                <option value="">-Select-</option>
                                <option value="Intend to Apply">Intend to Apply
                                </option>
                                <option value="Rejected">Rejected</option>
                                <option value="Accepted">Accepted</option>
                                <option value="Waitlisted">Waitlisted   </option>
                                <option value="WL, Accepted">WL, Accepted   </option>
                                <option value="WL, Rejected">WL, Rejected   </option>
                                <option value="Pending">Pending</option>
                            </select>
                        </span></p>

                        <p class="gdlr-lms-half-left">
            <label >Program*</label>
            <span class="gdlr-lms-combobox" >
                            <select  name="program" id="program" style="width: 100%;">
                                <option value="">-Select-</option>
                                <option value="Full Time">Full Time</option>
                                <option value="Part Time">Part Time</option>
                        
                            </select>
                        </span></p>
                        
                        

                        <p class="gdlr-lms-half-left">
            <label >Round's Applied</label>
            <span class="gdlr-lms-combobox" style="width: 158px;">
                        <select name="choice" id="program">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="N/A">N/A</option>
                        
                            </select>                   
                    </span> </p>
                    <p class="gdlr-lms-half-left">
            <label >Date Applied</label>
            <span class="gdlr-lms-combobox" >
                       <input type="text" name="received" id="received"  placeholder="DD/MM/YYYY" style="  background-color: white;" type="text" onfocus="(this.type='date')" >                  
                    </span> </p>
                   <p class="gdlr-lms-half-left">                                                 
            <label>Scholarship</label>
            <input type="text" name="scholarship"  value=""  style="width:87%">&nbsp<span><i class="gdlr-icon icon-dollar" style="color: #333333; font-size: 20px; "></i></span></p>
            <p class="gdlr-lms-half-left">
            <label >Date Decision Received</label>
            <span class="gdlr-lms-combobox" >
                      <!--  <input type="date" name="descion" id="descion"  placeholder="MM/DD/YYYY"  >  -->
                        <input placeholder="DD/MM/YYYY" name="descion" class="textbox-n" type="text" onfocus="(this.type='date')"  id="descion" style="  background-color: white;">                 
                    </span> </p>
                     <div style="width:100%;  text-align: center;">
                          <input type="submit" class="gdlr-button medium" style="color:#ffffff; background-color:#4f8ed6; " value="Add Application" />
             &nbsp
            <button class="gdlr-button medium" style="color:#ffffff; background-color:#d6724f;margin-top:0px;"><a href="<%=profile_index_path %>" style='color:inherit'>Cancel</a></button>

                     </div>


                    <%end %>
                    <div class="clear"></div>
</div>
<div class="profile_blog_rgt" style="border:none">
                <%#= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                <%=image_tag '3.jpg' %>
                </div>
</div>
</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 <script type="text/javascript">
$(document).ready(function(){
    
 $('#intqyes').click(function(){
        
         $('#intdate').css('display','block');
            
        
        
 });
 $('#intqno').click(function(){
        
     $('#intdate').css('display','none');
 });
});
</script>

app/views/schools/ranking.html.erb
 
<div class="gdlr-item gdlr-divider-item"></div>
<div class="gdlr-lms-container gdlr-lms-container">
        <div class="gdlr-lms-item">
 <div  class= "ten column" id='profind'>
<div style="margin-top:18px">
<div class="gdlr-item gdlr-tab-item horizontal" id="table">
<div class="tab-title-wrapper">
    <a href="<%=schools_path %>">
        <h4 class="tab-title ">
        <span>MBA Schools list</span></h4>
    </a>
    <a href="<%=schools_ranking_path %>"><h4 class="tab-title active"><span>By Ranking</span></h4></a>
    <!-- <a href="<%=schools_name_path %>"><h4 class="tab-title"><span>By Name</span></h4></a> -->
    <a href="<%=schools_state_path %>"><h4 class="tab-title"><span>By State</span></h4></a>
    <div class="gdlr-lms-content">

        
<div>
    <!-- #Temproray -->
     
</div>
    <!-- <div class="well"  > -->
        <div>
         
            <table width="100%" border="1" cellspacing="8" cellpadding="0" class="drawreq_table">
                       <tr><th id="th" style="border-right:none;border-bottom:none"></th>
                <th id ="th" style="border-left:none" rowspan="2"  width="38%">Business School</th>
                <th id ="th" rowspan="2" width="4%">University</th>
                <th id ="th" rowspan="2" width="4%">State</th>
                <th id ="th" rowspan="2" width="4%">City</th>
                <th id ="th" colspan="4" width="27%">Ranks</th>
                        </tr>
                        <tr>

                        <th  id ="th" width="12%" style="border:#3E6AA7;border-bottom:1px solid #000" ></th>
                        <th  id ="th" width="11%">Forbes</th>
                        <th id ="th">USN</th>
                    </tr>
                    <% @schools.each do |t| %>
                    <tr style="font-size:15px">
                            <td style="border-right:none"><img alt="Icon" src="<%= t.image.thumb('150x150').url %>" style="width: 60px; height: 41px;" />
                    </td>
                            <td style="border-left:none"> <a href="<%= school_appinfo_path(t.business_school) %>" style="color:#453232;">
                                    <%= t.business_school%>
                                    </a> </td>
                            <td style="color:#453232;"> <%=t.university %></td>
                            <td style="color:#453232;">
                    <%= State.find_by_id(t.state_id).name%></td>
                            
                            <td style="color:#453232;"><%=t.city %></td>
                            <td style="color:#453232;"><%=t.forbes %></td>
                    <td style="color:#453232;"><%=t.US_News_Ranking %></td>
                    
                    </tr>
                    <%end%>
                    
                    
               </table> 
        </div>
        <div class="gdlr-item gdlr-divider-item"></div>
        <%= will_paginate @schools, :class => 'gdlr-pagination'%>
    <!-- </div> -->
    <div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</div>
</div>
</div>
<div class="profile_blog_rgt" style="border:none">
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                </div>
</div>
</div>

app/views/schools/schoolappinfo.html.erb
<style>


#th {
    background-color: #3E6AA7;
    color:white;
   font-family: Verdana,Arial,Helvetica,sans-serif;
   font-weight: normal;padding: 9px;text-transform: uppercase;
   font-size: 14px;

    
}
.style-1 tr td{

	font-family: arial;
	font-size: 50;
}
</style>

<div class="gdlr-lms-content">
	<div class="two columns"><%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %></div>	
	<div class="eight columns">
	

		<div style="margin-left:1px;margin-right:1px">
			<div class="eleven columns">
				<div class="gdlr-item-title-wrapper gdlr-item pos-left borderme" style="margin-left: 1px;">
						<div class="gdlr-space" style="margin-top: 40px;"></div>
						<table class="style-2">
						<tbody style="text-align:left">
						<tr>
							<th id="th" colspan="3">Name</th>
							<th id="th" colspan="3">Email</th>
							<th id ="th"colspan="2">scholarship</th>
							<th id ="th"colspan="2">status</th>
						</tr>
							<% unless @school.nil? %>
								
							
							<tr>
								<td colspan="3" style="padding:10px"> 
									
										<% 
											@user=Member.find_by_id(@school.user_id) 
											@user.username
											# binding.pry
										%> 
									<a href="<%= static_profile_path(@user.username) %>" style="text-decoration:underline;"> 
										<%= @user.username  %>
									</a>
								</td> 
								<td colspan="3" style="padding:10px"> 
									
										<% 
											@user=Member.find_by_id(@school.user_id) 
											@user.email
											# binding.pry
										%> 
										<%= @user.email %>
									
								</td> 
								 
								<td colspan="2" style="padding:10px"> 
									<%= @school.scholarship  %>
								</td>	
								<td colspan="2" style="padding:10px"> 
									<%= @school.status	 %>
								</td>	

											
							</tr>
							<% else %>
								<tr>
									<td colspan="10" style="padding:10px; text-align:center;font-size:20px;"> 
										No Records......
									</td> 
												
								</tr>
							<% end %>
							
						</tbody>
						</table>
				</div>
				
			</div>
			<div class="one columns"></div>
		</div>
	</div>

	<div class="one columns"></div>
	<div class="one columns">
		<div class="google_adsense skyscraper" style="padding-left: 18px;">
			<%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
		</div>
		</div>
		<div class="clear"></div>
		
</div>

app/views/schools/state.html.erb
 
<div class="gdlr-item gdlr-divider-item"></div>
<div class="gdlr-lms-container gdlr-lms-container">
        <div class="gdlr-lms-item">
 <div  class= "ten column" id='profind'>
<div style="margin-top:18px">
<div class="gdlr-item gdlr-tab-item horizontal" id="table">
<div class="tab-title-wrapper">
    <a href="<%=schools_path %>">
        <h4 class="tab-title ">
        <span>MBA Schools list</span></h4>
    </a>
    <a href="<%=schools_ranking_path %>"><h4 class="tab-title"><span>By Ranking</span></h4></a>
    <!-- <a href="<%=schools_name_path %>"><h4 class="tab-title"><span>By Name</span></h4></a> -->
    <a href="<%=schools_state_path %>"><h4 class="tab-title active"><span>By State</span></h4></a>
    <div class="gdlr-lms-content">

        
<div>
    <!-- #Temproray -->
     
</div>
    <!-- <div class="well"  > -->
        <div>
         
            <table class="style-2">
						<tbody style="text-align:left">
						<tr>
							<!-- <th id="th"> Icon</th> -->
							<th id="th" >State</th>
							<th id ="th">School</th>
						</tr>
							<% @states.each do |t| %>
							 <tr style="font-size:15px; ">
							 	
								<td style="padding:10px;color: #453232;"> 
								<%= t.name %></td>
                                <td style="padding:10px;text-align:left"> 
                                <% a= School.where("state_id= ?" , t.id) %>
                                
                   				<% a.each_with_index do |key, index| %>
                   		
                              <%= index+1  %>) <a href="<%= school_appinfo_path(key.business_school) %>" style='color: #453232;'>
                                <%= key.business_school %> </a><br>		
                              	
                                 <%end%>
                                 

                                 </td>
							</tr>
							<%end %>
						</tbody>
						</table>
        </div>
        <div class="gdlr-item gdlr-divider-item"></div>
        <%= will_paginate @states, :class => 'gdlr-pagination'%>
    <!-- </div> -->
    <div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</div>
</div>
</div>
<div class="profile_blog_rgt" style="border:none">
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                <%= ad_unit(:skyscraper, "pub-6430317842295107", {:slot => "5305317726"}) %>
                </div>
</div>
</div>