config/routes.rb
  Rails.application.routes.draw do

  get 'colleges/index/:stateid' => 'colleges#index', :as => 'college_index'
  get 'colleges/searchusers/:username' => 'colleges#searchusers', :as => 'colleges_search'

  get 'mailboxes/mailbox'
  get 'mailboxes/show/:id' => "mailboxes#show", :as => 'mailboxes_show'
  post 'mailboxes/compose'
  get 'mailboxes/destroy/:id' => 'mailboxes#destroy', :as => 'mailboxes_destroy'
  get 'mailboxes/new'
  post 'mailboxes/save'
  get 'mailboxes/outbox'
  get 'mailboxes/newest'
  get 'mailboxes/outboxdel/:id' => 'mailboxes#outboxdel', :as => 'mailboxes_outboxdel'

  get 'schools/index', :as => 'schools'
  get 'schools/profile'
  get 'schools/name'
  get 'schools/search'
  post 'schools/create'
  post 'profile/stuff' => 'profile#stuffupdate', :as => 'stuffs'
  patch 'profile/stuff' => 'profile#stuffupdate', :as => 'stuff'
  get 'profile/viewusers' => 'profile#viewUsers', :as => 'profile_viewusers'
  get 'profile/searchuser'
  get 'schools/edit/:id' => 'schools#edit',  as: 'schools_edit'
  patch 'schools/update/:id' => 'schools#update', as: 'schools_update'
  get 'schools/destroy/:id' => 'schools#destroy', :as => 'schools_destroy'
  get 'schools/ranking'
  get 'schools/state'
  get 'schools/statelist'
  get 'forums/index'
  get 'forums/:id/topics' => 'forums#topics', :as => 'forum_topic'
  post 'forums/topics/new' => 'forums#topic_new', :as => 'topic_new'
  get 'forums/topics/:topic/posts' => 'forums#posts', :as => 'forum_posts'
  post 'forums/posts/new' => 'forums#post_new', :as => 'post_new'
  get 'forums/new'
  # get 'forums/:id' => 'forums#show'
  get 'forums/post/:id' => 'forums#post', as: 'forum_post'
  post 'forums/create'
  post 'forums/postcreate'
  get 'forums/forumsearch'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
   

  get 'authentications/index'

  get 'members/index' #(signuup)
  get 'members/signup'
  post 'members/create'
  #get 'members/login'
  get 'members/verifieamil/:token' => 'members#verifiemail', as: 'member_verify'
  get 'members/collage/:stateid' => 'members#collage', as: 'member_collage'
  
  root 'homepage#index'

  get 'homepage/create'
  
  get 'myadvices/myadvice'
  get 'myadvice/blog/:id' => 'myadvices#blogdata', as: 'myadvices_blog' 
  get 'myadvices/new'
  post 'myadvices/create'
   # get 'admin/show/:id' => 'admins#show', as: 'show_admin'
  get 'announces/index'
  get 'announces/single/:id' => 'announces#single', as: 'announces_announce'
  get 'auth/:provider/callback' => 'authentications#create' 
  get 'logout' => 'authentications#destroy'

  get 'members/index'
  
  post 'subscribes/subscribe' 
  get 'subscribes/confirm/:token' => 'subscribes#confirm', as: 'subscribes_confirm'

  post 'subscribes/submitcontact'
  get 'subscribes/contactus'

  #--------profile routes-------------#
  get 'profile/index' => 'profile#index', :as => 'profile_index'
  get 'profile/login'
  post 'profile/create'
  get 'profile/mailbox'
  get 'profile/show/:id' => "profile#show", :as => 'profile_show'
  post 'profile/compose'
  get 'profile/destroy/:id' => 'profile#destroy', :as => 'profile_destroy'
  get 'profile/new'
  post 'profile/save'
  get 'profile/edit'
  post 'profile/update'
  get 'profile/settings'
  post 'profile/profilecreate'
  get 'profile/chnagepwd'
  post 'profile/changepwdcreate'
  get 'profile/forgotpassword'
  post 'profile/createforgotpassword'
  get 'profile/updatepassword/:token' => 'profile#updatepassword', :as => 'profile_updatepwd'
  post 'profile/createupdatepwd'
  get 'profile/profileupdates'
  get 'profile/schoolapplied'
  get 'profile/searchschool'
  get 'profile/like/:cuserid/:buserid' => 'profile#like', :as => 'profile_like'
  get 'profile/dislike/:cuserid/:buserid' => 'profile#dislike', :as => 'profile_dislike'
  get  'profile/commitschool/:cuurentuserid/:schoolname' => 'profile#commitschool', :as => 'profile_commitschool'
  get 'profile/comndestroy/:id' => 'profile#comndestroy', :as => 'profile_comndestroy'
  # resources :schools

  get 'member/:username' => 'profile#staticprofile', :as => 'static_profile'
  get 'profile/staticprofile'
  get 'profiles/all' => 'profile#staticbulk'
  get 'user/bookmark/:currentuserid/:bookmarkuserid' => 'profile#bookmark', :as => 'member_bookmark'
  get 'user/remove/:id' => 'profile#remove', :as => 'user_remove'
  
  post 'comments/create' => 'profile#commentcreate', :as => 'comment_new'
  post 'prof_cmn/create' => 'profile#prof_cmn_create', :as => 'prof_cmn_new'
  get 'profile/topusers' => 'profile#topusers', :as => 'topusers'
  
  get 'profile/bookmarklist'
  get 'bookmark/remove/:id' => 'profile#removebookmarklist', :as => 'booklist_remove'

  get 'schools/schoolappinfo/:schoolname' => 'schools#schoolappinfo', :as => 'school_appinfo'
  get 'profile/name' => 'profile#name', :as => 'profile_name'
  



end

app/models/announce.rb
class Announce < ActiveRecord::Base
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
end

app/models/breaking.rb
class Breaking < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, presence: true
	
	validates :email, format: /@/
end

app/models/cstate.rb
class Cstate < ActiveRecord::Base
	has_many :users, dependent: :delete_all
end

app/models/extras.rb
class Extra < ActiveRecord::Base

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
	include BCrypt
	validates :username,  presence: { message: "does not exist" }
	validates :username, uniqueness: true
	validates :username, length: {maximum: 30, minimum: 6 }
	validates :email, presence: true
    validates :undergraduate_school, presence: true               
	validates :email, uniqueness: true
	validates :email, format: /@/
	validates :friend, format: /@/,presence: { message: "email is written in wrong format" }
	validate :username, :uniqueness => {:case_sensitive => false}
	validates :gpa, presence: true
	validates_numericality_of :gpa , :less_than_or_equal_to=>4.00, :greater_than_or_equal_to=>1.00
    validates :gmat_score, presence: true
	validates_numericality_of :gmat_score , :less_than_or_equal_to=>800, :greater_than_or_equal_to=>200

	# validates :password, :presence =>true,
 #                    :length => { :minimum => 5, :maximum => 40 },
 #                    :confirmation =>true
	dragonfly_accessor :image
	has_one :stuff
	has_many :posts
	has_many :topics
	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |member|
			member.provider = auth.provider 
			member.uid      = auth.uid
			member.name = auth.info.name
			member.email = auth.info.email
			member.save
		end
	end

	def password

    	@password ||= Password.new(password_hash)
 	end
	def password=(new_password)
    	@password = Password.create(new_password)
    	self.password_hash = @password
 	end
 	def self.authenticate(username, password)
 		user = self.find_by_email(username) || self.find_by_username(username)
 		unless user.nil?
 			user.id if BCrypt::Password.new(user.password) == password && user.active
 		end
 	end


end

app/models/myadvice.rb
class Myadvice < ActiveRecord::Base
	belongs_to :Refblog
end

app/models/outbox.rb
class Outbox < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :member
end

app/models/refblog.rb
class Refblog < Refinery::Core::BaseModel
  self.table_name = 'refinery_blogposts'
  has_many :myadvices
end

app/models/reply.rb
class Reply < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
	dragonfly_accessor :image
	validates :school, :presence => true
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :schools
end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
	belongs_to :member
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :forum
	has_many :posts, :dependent => :destroy
	belongs_to :member
	default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base

	include BCrypt
	def password
    @password ||= Password.new(password_hash)
 end

 def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
 end
end

app/models/ustate.rb
class Ustate < ActiveRecord::Base
	has_many :ucollege
end

app/views/layouts/_footer.html.erb
 <footer class="footer-wrapper">
				<div class="footer-container container" style="padding: 0;">
										<div class="footer-container container">
	<div class="footer-column three columns" id="footer-widget-1">
	<div id="text-5" class="widget widget_text gdlr-item gdlr-widget">  <a href="<%=root_url %>"><%=image_tag 'logo@2X_white.png', :style => 'width: 256px;
'%></a> <div class="clear"></div>			
	<div class="textwidget"></div>
	<!-- <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p> -->
</div>
    </div>	
    </div>

										<div class="footer-column four columns widget widget_recent_entries gdlr-item gdlr-widget" id="footer-widget-2" style="margin-right: 3%;margin-left: 8px;margin-bottom: 0;">
	  <div id="gdlr-lms-recent-course-widget-2" class="widget widget_gdlr-lms-recent-course-widget gdlr-item gdlr-widget">
		<h3 class="gdlr-widget-title" style="font-family:arial;font-size: 13px;
" >Quick links</h3><div class="clear"></div>		
		<ul style='list-style:none'>
			<li><a href="<%=root_url %>">Home</a></li>
			<li><a href="<%=profile_index_path %>">Profiles</a></li>
			<li><a href="<%=schools_path%>">Schools</a></li>
			<li><a href="<%=myadvices_myadvice_path %>">My Advice</a></li>
			<li><a href="<%=forums_index_path %>">Forum</a></li>
			<li><a href="<%= subscribes_contactus_path %>">Contact Us</a></li>
			   <li><a href="#">Privacy Policy</a></li>
		</ul>
		</div>
	</div>
										<div class="footer-column four columns" id="footer-widget-3"  >
	<%=form_tag subscribes_subscribe_path, :class => 'gdlr-lms-form' do | f |  %>
		<h3 class="gdlr-widget-title" style="font-family:arial;font-size: 13px;
">Email Newsletter</h3>
			<p class="is-hidden-desktop" id ="color"><b style="font-size: 15px;font-family:arial;font-size: 13px;
">Subscribe for monthly updates and to receive inspiration, ideas, and news in your inbox</b></p>
		<p style="font-family:arial;font-size: 13px;">Your Email (required)&nbsp&nbsp&nbsp
		<span id="error" style="color:red;"></span><br>
	    <span class="wpcf7-form-control-wrap your-email">
	    	<%=text_field_tag :email, '',:id => "email" %>
	    </span> </p>
		<%=submit_tag 'Subscribe', :style => 'padding:12px;width:100%;margin: 0px;margin-top: -10px;' , :onclick => 'return validateform();' %>
	<% end %>
	<div class="gdlr-item gdlr-divider-item"></div>
    <div class="clear"></div>
    <div id="text-8" class="widget widget_text gdlr-item gdlr-widget" style="margin: 0"><h3 class="gdlr-widget-title" style="font-family:arial;font-size: 13px;">Social Media</h3><div class="clear"></div><div class="textwidget"><a href="https://www.facebook.com/pages/Mbanumbers/1619282458305903?skip_nax_wizard=true&ref_type=bookmark" target="_blank"><i class="gdlr-icon icon-facebook" style="color: #bfbfbf; font-size: 15px; "></i></a> <a href="https://twitter.com/infombanumbers" target="_blank"><i class="gdlr-icon icon-twitter" style="color: #bfbfbf; font-size: 15px; "></i></a> <a href="https://plus.google.com/111198438646871692348/about?hl=en-GB&service=PLUS" target="_blank"><i class="gdlr-icon icon-google-plus" style="color: #bfbfbf; font-size: 15px; "></i></a> <a href="https://www.linkedin.com/pub/info-mbanumbers/b3/891/bb9" target="_blank"><i class="gdlr-icon icon-linkedin" style="color: #bfbfbf; font-size: 15px; "></i></a>

</div>
</div>
	</div>
										
									<div class="clear"></div>
		</div>
				
				<div class="copyright-wrapper">
			<div class="copyright-container container">
				<div class="copyright-left">
					MBA Numbers				</div>
				<div class="copyright-right">
					Copyright © 2014 - All Right Reserved - MBA Numbers 				</div>
				<div class="clear"></div>

			</div>
		</div>
		<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>

			</footer>
 			<script type="text/javascript">
	function validateform()
	{
		var email=document.getElementById('email').value
		var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    
		if(email == "")
		{
			document.getElementById('error').innerHTML ="Please Enter Email";
			return false;
		}
		else if(!re.test(email))
		{
			document.getElementById('error').innerHTML ="Please Enter Valid Email";
			return false;
		}
		
	}
 </script>

app/views/layouts/_logo_with_mobile_menu.html.erb
<div class="gdlr-logo" style="width: 283px;height: 80px;padding-top: 0px;padding-bottom: 0px;margin-bottom: 7px;margin-top:7px;text-align: left;">
					<a href="<%=root_url%>">
						
						<%= image_tag 'logo@2X.png', :style=>'width: 75%;
height: 75%; margin-top:15px;'%>					
					</a>
									
</div>

app/views/layouts/_navigation.html.erb
<div id = "nav">

<header class="gdlr-header-wrapper" style="line-height: 19px;">
<div class="gdlr-header-inner" style="font-size: 13px;">
<div class="gdlr-header-container container">
<!-- logo -->
<div class="gdlr-logo">
<div class="crebuttons">
<% if current_user.nil? %>
				<a href=""></a>
				<%else %>
					<a class="gdlr-button small" href="<%=profile_index_path%>"  style="color:#ffffff; background-color:#fcaa0c; width: 135px;">
					<span class="gdlr-icon  icon-user" style="color: #4F4F4F;font-size: 16px;"></span>My Profile</a>
					<%end %>
<% if current_user.nil? %>
<a class="gdlr-button small" href="<%=profile_login_path %>" style="color:#ffffff; background: #989490; ">Student Login</a>
<%else %>
<a class="gdlr-button small" href="/logout" style="color:#ffffff; background: #989490; ">Logout</a>
<%end %>
<% if current_user.nil? %>
<a class="gdlr-button small" href="<%=members_signup_path%>" style="color:#ffffff; background-color:#fcaa0c; ">Enroll Now</a>
<%else %>
<a class="gdlr-button small" href="<%= profile_settings_path %>"  style="color:#ffffff; background-color:#fcaa0c; width:112px ">
				<span class="gdlr-icon icon-gears" style="color: #4F4F4F;font-size: 16px;"></span>Settings
				</a>
				<% end %>

</div>
<div class="gdlr-responsive-navigation dl-menuwrapper" id="gdlr-responsive-navigation" >
<!--------- Mobile ----------- -->
<button class="dl-trigger">Open Menu</button>
<ul id="menu-main-menu" class="dl-menu gdlr-main-mobile-menu">
<li id="menu-item-3263" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263"><a href="<%= root_path %>">Home </a></li>
<li id="menu-item-3383" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-3383"><a href="<%= profile_index_path %>">Profile Search</a>
<ul class="dl-submenu">
<li id="menu-item-3319" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-3312 current_page_item menu-item-3319"><a href="<%= topusers_path %>">NEWEST PROFILES</a></li>
<li id="menu-item-3318" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3318"><a href="<%=profile_profileupdates_path %>">RECENTLY UPDATED</a></li>
<!-- <li id="menu-item-3320" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-3320"><a href="http://themes.goodlayers.com/clevercourse/author/rebeccasm/">By GMAT</a></li>
<li id="menu-item-3325" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3325"><a href="#">By GPA</a></li> -->
<li id="menu-item-3455" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3455"><a href="<%= profile_name_path %>">SEARCH BY NAME</a></li>
<li id="menu-item-3455" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3455"><a href="<%= profile_schoolapplied_path %>">SEARCH BY SCHOOL APPLIED</a></li>
</ul>
</li>
<li id="menu-item-3132" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3132">
<a href="<%= schools_path %>">MBA Schools</a>
<ul class="dl-submenu">
<li id="menu-item-3131" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3131">
<a href="<%= schools_ranking_path %>">BY RANKING</a>
</li>

<li id="menu-item-3162" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3162">
<a href="<%= schools_state_path %>">BY STATE</a>
</li>
</ul>
</li>
<li id="menu-item-3344" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3344">
<a href="<%= myadvices_myadvice_path %>">My Advice</a>
</li>
<li id="menu-item-3046" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3046">
<a href="<%= forums_index_path %>">Forum</a>
</li>
<li id="menu-item-3040" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3040">
<a href="<%= subscribes_contactus_path %>">Contact Us</a>
</li>
</ul>
</div>
</div>
<!-------------------- Mobile end ------------>
<!-- navigation -->
<!----------------- Desk top start ------------- -->
 <div class="gdlr-navigation-wrapper" style="margin-top:112px;padding-top: 3px;
margin-top: 0px;">
<div class="crebuttons">
<a class="gdlr-button small" href="#" style="color:#ffffff; background: #989490; ">Student Login</a>
<a class="gdlr-button small" href="#" style="color:#ffffff; background-color:#fcaa0c; ">Enroll Now</a>
</div>
<nav class="gdlr-navigation" id="gdlr-main-navigation" role="navigation">
<ul id="menu-main-menu-1" class="sf-menu gdlr-main-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu">
<a href="<%= root_path %>" style="font-weight:700;color:black;font-size: 100%;margin-top: 12px; font-family:arial" onclick="return validate();"><strong>
	<b>Home</b> </strong></a> 
</li>

<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu" style="margin-top: 12px;opacity: 2.5" >
<label style="margin-top: 12px;
">|</label> 
</li>

<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-3383menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-3383 gdlr-normal-menu" style="margin-left: 12px;">
<a href="<%= profile_index_path %>" style="font-weight:700;color:black;font-size: 100%;opacity: 2.5;margin-top: 12px;

font-family:arial">Profile Search</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-3312 current_page_item menu-item-3319">
<a href="<%= topusers_path %>" style="font-size: 100%;font-family:arial">NEWEST PROFILES</a>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3318">
<a href="<%=profile_profileupdates_path%>" style="font-size: 100%;font-family:arial">RECENTLY UPDATED</a></li>

<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3455">
<a href="<%= profile_name_path %>" style="font-size: 100%;font-family:arial">SEARCH BY NAME</a>
</li>
<li id="menu-item-3455" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3455"><a href="<%= profile_schoolapplied_path %>">SEARCH BY SCHOOL APPLIED</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu" style="margin-top: 12px;opacity: 2.5">
<label style="margin-top: 12px;">|</label> 
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-3383menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-3383 gdlr-normal-menu" style="margin-left:12px;">
<a href="<%= schools_path %>" style="font-weight:700;color:black;font-size: 100%;opacity: 2.5;margin-top: 12px;font-family:arial
">MBA Schools</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-3312 current_page_item menu-item-3319">
<a href="<%= schools_ranking_path %>" style="font-size: 100%;font-family:arial">BY RANKING</a>
</li>

<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-3320">
<a href="<%= schools_state_path %>" style="font-size: 100%;font-family:arial">BY STATE</a>
</li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu" style="margin-top: 12px;opacity: 2.5">
<label style="margin-top: 12px;">|</label> 
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3344menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3344 gdlr-normal-menu" style="margin-left:12px;">
	<a href="<%= myadvices_myadvice_path %>" style="font-weight:700;color:black;font-size: 100%;margin-top: 12px;font-family:arial
">My Advice</a>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu" style="margin-top: 12px;opacity: 2.5">
<label style="margin-top: 12px;">|</label> 
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3046menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3046 gdlr-normal-menu" style="margin-left:12px;margin-top: 12px;">
	<a href="<%= forums_index_path %>" style="font-weight:700;color:black;
	font-size: 100%;
	font-family:arial">Forum</a>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3263menu-item menu-item-type-post_type menu-item-object-page menu-item-3263 gdlr-normal-menu"style="margin-left:12px;margin-top: 12px;opacity: 2.5">
<label style="margin-top: 12px;">|</label> 
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3040menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3040 gdlr-mega-menu" style="margin-left:12px;font-family:arial">
<a href="<%= subscribes_contactus_path %>" style="font-weight:700;color:black;
font-size: 100%;margin-top: 12px;font-family:arial
">CONTACT</a>
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
</li>
</ul>
</nav>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</div>
<div class="clear"></div>
</header>
</div>
<style>
	a:hover {
    color: #FF00FF;
}
a:active {
    color: #0000FF;
}
</style>

app/views/layouts/_slider.html.erb
<section id="content-section-1" >
   <div class="owl-carousel">
   <div class="item">
       <%= image_tag 'banner12.jpg', :style => "height: 275px;" %> 
    </div>
    <div class="item">
       
       <%= image_tag 'banner11.jpg', :style => "height: 275px;"  %>
    </div>
       
   </div>
</section>

app/views/layouts/college.html.erb
<!DOCTYPE html>
<!--[if IE 7]><html class="ie ie7 ltie8 ltie9" lang="en-US"><![endif]-->
<!--[if IE 8]><html class="ie ie8 ltie9" lang="en-US"><![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="initial-scale = 1.0" />
	
	<title>MBA Numbers</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	
	<%= csrf_meta_tags %>	
	<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
	
</head>
<body>
	<!-- <h1> hello </h1> -->
	<%yield%>


 </body>

</html>